project_id = "xghhumucsccbfmpdexsr"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.setup-test-users]
verify_jwt = false

[functions.export-table-data]
verify_jwt = false

[functions.import-insights]
verify_jwt = false

[functions.scheduled-export]
verify_jwt = false

[functions.sync-analytics]
verify_jwt = false
