/**
 * validate.js — Zod-based input validation middleware for LYNE backend
 *
 * Usage:
 *   const { validate, schemas } = require('../middleware/validate');
 *   router.post('/path', validate(schemas.createBranch), handler);
 *
 * The middleware validates req.body against the provided Zod schema.
 * On failure it returns HTTP 400 with the first validation error message.
 * On success it replaces req.body with the parsed (sanitized) data.
 */
const { z } = require('zod');
const idSchema = z.string().min(1).max(64);

// ── Validation middleware factory ─────────────────────────────
function validate(schema) {
  return (req, res, next) => {
    const result = schema.safeParse(req.body);
    if (!result.success) {
      const message = result.error.issues?.[0]?.message || 'Invalid request data.';
      return res.status(400).json({ error: message });
    }
    // Replace body with sanitized/parsed data
    req.body = result.data;
    next();
  };
}

// ── Shared schemas ────────────────────────────────────────────
const schemas = {
  // Auth
  /* No national_id or trn: identification is kept in the device keychain by the
     app and never sent here. Declaring them would invite a client to send what
     the server now silently drops. */
  syncUser: z.object({
    full_name:     z.string().min(1).max(255).optional(),
    phone:         z.string().max(50).optional(),
    date_of_birth: z.string().regex(/^\d{4}-\d{2}-\d{2}$/, 'date_of_birth must be YYYY-MM-DD').optional(),
  }),

  // Staff invite
  staffInvite: z.object({
    email:       z.string().email('A valid email is required'),
    full_name:   z.string().min(1).max(255),
    role:        z.enum(['line_staff', 'manager', 'executive']),
    business_id: idSchema,
    branch_id:   idSchema.optional(),
  }),

  // Businesses
  createBusiness: z.object({
    name:                 z.string().min(1).max(255),
    slug:                 z.string().min(1).max(100).regex(/^[a-z0-9-]+$/, 'slug must be lowercase alphanumeric with hyphens'),
    description:          z.string().max(1000).optional(),
    logo_url:             z.string().url().optional(),
    website_url:          z.string().url().optional(),
    phone:                z.string().max(50).optional(),
    email:                z.string().email().optional(),
    subscription_tier_id: idSchema,
  }),

  /* Branches. The eight fields below opening_time were absent, and because a
     Zod object STRIPS what it does not declare, wiring this schema before they
     were added would have silently dropped a branch's hours, coordinates and
     parish on every create — and branchOpenInfo() would then have fallen back
     to default agency hours for a branch that had none. That is the "screen
     lies when the data is missing" failure, manufactured by a validator. */
  createBranch: z.object({
    business_id:    idSchema,
    name:           z.string().min(1).max(255),
    address:        z.string().max(500).optional(),
    city:           z.string().max(100).optional(),
    parish:         z.string().max(100).optional(),
    phone:          z.string().max(50).optional(),
    email:          z.string().email().optional(),
    photo_url:      z.string().url().optional(),
    latitude:       z.coerce.number().min(-90).max(90).optional(),
    longitude:      z.coerce.number().min(-180).max(180).optional(),
    opening_time:   z.string().regex(/^\d{2}:\d{2}(:\d{2})?$/, 'opening_time must be HH:MM or HH:MM:SS').optional(),
    closing_time:   z.string().regex(/^\d{2}:\d{2}(:\d{2})?$/, 'closing_time must be HH:MM or HH:MM:SS').optional(),
    open_days:      z.string().regex(/^[0-6](,[0-6])*$/, 'open_days must be comma-separated day numbers, 0=Sunday').max(20).optional(),
    is_main_branch: z.coerce.boolean().optional(),
    is_active:      z.coerce.boolean().optional(),
  }),

  // Services
  createService: z.object({
    business_id:           idSchema,
    name:                  z.string().min(1).max(255),
    description:           z.string().max(1000).optional(),
    ticket_prefix:         z.string().max(10).optional(),
    base_avg_time_minutes: z.coerce.number().int().min(1).max(480).optional(),
    is_active:             z.boolean().optional(),
  }),

  // Queues
  createQueue: z.object({
    branch_id:    idSchema,
    service_id:   idSchema,
    queue_date:   z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional(),
    max_capacity: z.coerce.number().int().min(1).max(1000).optional(),
  }),

  // Tickets
  joinQueue: z.object({
    queue_id:  idSchema,
    form_data: z.record(z.unknown()).optional(),
  }),

  updateTicketStatus: z.object({
    new_status: z.enum(['in_service', 'served', 'left', 'cancelled']),
    notes:      z.string().max(1000).optional(),
  }),

  /* Staff. Two deliberate omissions.

     `staff_code` is generated by the handler from the business slug, so a
     client-supplied one was never used — declaring it would invite callers to
     send a value that silently does nothing.

     `supabase_uid` is omitted so the validator STRIPS it. The handler already
     refuses to bind it (see the role grant guard in routes/staff.js), and this
     is the second lock on the same door: an identity binding must come from a
     verified token, never from a typed field. */
  createStaff: z.object({
    business_id:         idSchema,
    branch_id:           idSchema.optional(),
    role_id:             idSchema,
    full_name:           z.string().min(1).max(255),
    email:               z.string().email(),
    phone:               z.string().max(50).optional(),
    assigned_service_id: idSchema.optional(),
    availability_status: z.enum(['active', 'on_leave', 'inactive']).optional(),
  }),

  /* Notifications. The previous schema (title/body/type/data) described an
     endpoint that does not exist — the handler and the `notifications` table
     both speak user_id/ticket_id/notification_type/channel/message. Wiring the
     old one would have rejected every legitimate call with "Invalid request
     data" while passing nothing useful through. */
  sendNotification: z.object({
    user_id:           idSchema,
    ticket_id:         idSchema.optional(),
    notification_type: z.string().min(1).max(50).optional(),
    channel:           z.string().min(1).max(20).optional(),
    message:           z.string().min(1).max(2000),
  }),

  /* Predictions. The six provenance fields were missing, and they are the ones
     that make a stored insight auditable — which window it was computed over,
     how many records it saw, and when it goes stale. Stripping stale_after in
     particular would have made every insight immortal, because the reader
     treats NULL as "never expires". */
  savePrediction: z.object({
    business_id:         idSchema,
    branch_id:           idSchema.optional(),
    service_id:          idSchema.optional(),
    insight_type:        z.string().min(1).max(100),
    insight_data:        z.record(z.unknown()),
    model_version:       z.string().max(50).optional(),
    generated_at:        z.string().optional(),
    records_processed:   z.coerce.number().int().min(0).optional(),
    source_window_start: z.string().optional(),
    source_window_end:   z.string().optional(),
    stale_after:         z.string().optional(),
  }),

  /* ────────────────────────────────────────────────────────────────────────
     The remaining 20. Two rules held throughout:

     1. PUT schemas are PARTIAL. Every field optional, because these handlers
        update with COALESCE(?, column) — a required field would reject every
        partial save the admin app makes.
     2. Where a handler already normalises or clamps, the schema validates the
        SHAPE and leaves the range alone. Duplicating a clamp as a strict range
        turns "silently corrected" into "400", which is a behaviour change
        wearing a security costume.
     ──────────────────────────────────────────────────────────────────────── */

  // Analytics — handler clamps to 1..365, so only the shape is checked here.
  refreshAnalytics: z.object({
    lookback_days: z.coerce.number().int().optional(),
  }),

  createAssignment: z.object({
    staff_id:        idSchema,
    counter_id:      idSchema.optional(),
    assignment_date: z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional(),
    shift_start:     z.string().regex(/^\d{2}:\d{2}(:\d{2})?$/).optional(),
    shift_end:       z.string().regex(/^\d{2}:\d{2}(:\d{2})?$/).optional(),
  }),

  /* national_id and trn are declared because THIS BRANCH still writes them.
     Omitting them here would strip the fields and quietly change what the
     product stores — a privacy change belongs in the privacy commit, not as a
     side effect of a validation pass. The branch reconciliation removes both
     the columns' write path and these two lines together. */
  updateProfile: z.object({
    full_name:     z.string().min(1).max(255).optional(),
    phone:         z.string().max(50).optional(),
    date_of_birth: z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional(),
  }),

  forceSignout: z.object({
    target_supabase_uid: z.string().min(1).max(128),
  }),

  updateBranch: z.object({
    name:           z.string().min(1).max(255).optional(),
    address:        z.string().max(500).optional(),
    city:           z.string().max(100).optional(),
    parish:         z.string().max(100).optional(),
    phone:          z.string().max(50).optional(),
    latitude:       z.coerce.number().min(-90).max(90).optional(),
    longitude:      z.coerce.number().min(-180).max(180).optional(),
    opening_time:   z.string().regex(/^\d{2}:\d{2}(:\d{2})?$/).optional(),
    closing_time:   z.string().regex(/^\d{2}:\d{2}(:\d{2})?$/).optional(),
    open_days:      z.string().regex(/^[0-6](,[0-6])*$/).max(20).optional(),
    is_main_branch: z.coerce.boolean().optional(),
    is_active:      z.coerce.boolean().optional(),
  }),

  updateBusiness: z.object({
    name:                 z.string().min(1).max(255).optional(),
    description:          z.string().max(1000).optional(),
    logo_url:             z.string().url().optional(),
    website_url:          z.string().url().optional(),
    phone:                z.string().max(50).optional(),
    email:                z.string().email().optional(),
    subscription_tier_id: idSchema.optional(),
    is_active:            z.coerce.boolean().optional(),
  }),

  createCounter: z.object({
    branch_id:  idSchema,
    service_id: idSchema.optional(),
    label:      z.string().min(1).max(100),
  }),

  registerDevice: z.object({
    expo_push_token: z.string().min(1).max(255),
    platform:        z.enum(['ios', 'android', 'web']).optional(),
    device_name:     z.string().max(255).optional(),
  }),

  /* Wire names, not the handler's local aliases: it destructures
     `branch_id: branchId, request_type: requestType`. A schema written from the
     alias would reject every real request. */
  staffRequest: z.object({
    branch_id:    idSchema.optional(),
    message:      z.string().min(1).max(2000),
    request_type: z.string().max(50).optional(),
  }),

  attachPaymentMethod: z.object({
    payment_method_id: z.string().min(1).max(255),
  }),

  /* amount_cents is deliberately absent, so the validator strips it before the
     handler ever sees it. The handler no longer reads it either — two locks on
     the same door, because this one was a live "premium for $0.01". */
  createIntent: z.object({
    payment_method_id: z.string().min(1).max(255),
    idempotency_key:   z.string().min(1).max(255),
    purpose:           z.string().min(1).max(100).optional(),
    save_card:         z.coerce.boolean().optional(),
  }),

  pipelineTrigger: z.object({
    business_id:         idSchema,
    source_window_start: z.string().optional(),
    source_window_end:   z.string().optional(),
  }),

  pipelineImport: z.object({
    business_id:         idSchema,
    insights:            z.array(z.record(z.unknown())),
    model_version:       z.string().max(50).optional(),
    records_exported:    z.coerce.number().int().min(0).optional(),
    source_window_start: z.string().optional(),
    source_window_end:   z.string().optional(),
  }),

  updateService: z.object({
    name:                  z.string().min(1).max(255).optional(),
    description:           z.string().max(1000).optional(),
    ticket_prefix:         z.string().max(10).optional(),
    base_avg_time_minutes: z.coerce.number().int().min(1).max(480).optional(),
    is_active:             z.coerce.boolean().optional(),
  }),

  branchSettings: z.object({
    branch_id:      idSchema.optional(),
    allow_overflow: z.coerce.boolean().optional(),
  }),

  /* idle_after_minutes is a three-way: null and 'off' both mean "never", a
     number means a threshold. The handler already normalises all three and
     falls back to a default for anything else, so the schema only has to stop
     an object or an array getting that far. */
  alertPrefs: z.object({
    idle_after_minutes: z.union([z.number(), z.string(), z.null()]).optional(),
    line_over_target:   z.string().max(10).optional(),
  }),

  /* supabase_uid absent by design — same reasoning as createStaff. */
  updateStaff: z.object({
    branch_id:           idSchema.optional(),
    role_id:             idSchema.optional(),
    full_name:           z.string().min(1).max(255).optional(),
    email:               z.string().email().optional(),
    phone:               z.string().max(50).optional(),
    assigned_service_id: idSchema.optional(),
    availability_status: z.enum(['active', 'on_leave', 'inactive']).optional(),
    is_active:           z.coerce.boolean().optional(),
  }),

  // Targets — the handler clamps every number, so shape only.
  businessTargets: z.object({
    business_id:            idSchema.optional(),
    target_wait_minutes:    z.coerce.number().int().optional(),
    target_completion_rate: z.coerce.number().int().optional(),
    target_no_show_rate:    z.coerce.number().int().optional(),
    horizon_months:         z.coerce.number().int().optional(),
    note:                   z.string().max(1000).optional(),
  }),

  branchTargets: z.object({
    branch_id:              idSchema.optional(),
    target_wait_minutes:    z.coerce.number().int().optional(),
    target_completion_rate: z.coerce.number().int().optional(),
    target_no_show_rate:    z.coerce.number().int().optional(),
    note:                   z.string().max(1000).optional(),
  }),

  /* Subscriptions. `plan` is the only thing the client chooses, and it chooses
     from a list — the amount comes from lib/premium.js PLANS and is never
     accepted from a request. Same rule that closed "premium for one cent". */
  startSubscription: z.object({
    plan:              z.enum(['monthly', 'yearly']),
    payment_method_id: z.string().min(1).max(255),
    idempotency_key:   z.string().min(1).max(255),
  }),

  cancelSubscription: z.object({
    // Optional and free-text: useful to us, never a gate. Nobody has to explain
    // themselves to stop paying.
    reason: z.string().max(500).optional(),
  }),

  skipTicket: z.object({
    disposition: z.enum(['remove', 'requeue']).optional(),
  }),

};

module.exports = { validate, schemas };
