import * as React from 'react';
import { useQuery } from '@tanstack/react-query';
import { hasInsights, getInsightFreshness } from '@/lib/api/insights';
import { useStaffRole } from '@/hooks/useStaffRole';
import { PeakHoursHeatmap } from './PeakHoursHeatmap';
import { AnomalyAlerts } from './AnomalyAlerts';
import { AIRecommendations } from './AIRecommendations';
import { Skeleton } from '@/components/ui/skeleton';
import { AlertCircle, Clock, Database } from 'lucide-react';
import { formatDistanceToNow, parseISO } from 'date-fns';

interface InsightsPanelProps {
  className?: string;
}

export function InsightsPanel({ className }: InsightsPanelProps) {
  const { staffData } = useStaffRole();
  const organizationId = staffData?.organization_id;

  const { data: hasData, isLoading: checkingInsights } = useQuery({
    queryKey: ['has-insights', organizationId],
    queryFn: () => hasInsights(organizationId!),
    enabled: !!organizationId,
  });

  const { data: freshness } = useQuery({
    queryKey: ['insight-freshness', organizationId],
    queryFn: () => getInsightFreshness(organizationId!),
    enabled: !!organizationId && hasData,
  });

  if (checkingInsights) {
    return (
      <div className={className}>
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
          <Skeleton className="h-64 rounded-xl" />
          <Skeleton className="h-64 rounded-xl" />
          <Skeleton className="h-48 rounded-xl lg:col-span-2" />
        </div>
      </div>
    );
  }

  if (!hasData) {
    return (
      <div className={`glass rounded-xl p-8 text-center ${className}`}>
        <Database className="h-12 w-12 mx-auto mb-4 text-muted-foreground opacity-50" />
        <h3 className="text-xl font-semibold text-foreground mb-2">No Insights Available</h3>
        <p className="text-muted-foreground max-w-md mx-auto mb-6">
          Analytics insights are generated by running the Jupyter notebooks. 
          Once you run the notebooks and import the results, detailed insights will appear here.
        </p>
        <div className="bg-muted/50 rounded-lg p-4 max-w-lg mx-auto text-left">
          <p className="text-sm font-medium text-foreground mb-2">Quick Start:</p>
          <ol className="text-sm text-muted-foreground space-y-1 list-decimal list-inside">
            <li>Export CSV data using the edge function</li>
            <li>Run your Jupyter notebooks locally</li>
            <li>Import the JSON results back via the API</li>
          </ol>
        </div>
      </div>
    );
  }

  return (
    <div className={className}>
      {/* Freshness indicator */}
      {freshness && freshness.latestDate && (
        <div className="flex items-center gap-2 mb-4 text-sm text-muted-foreground">
          <Clock className="h-4 w-4" />
          <span>
            Last updated {formatDistanceToNow(parseISO(freshness.latestDate), { addSuffix: true })}
          </span>
          {freshness.ageInDays && freshness.ageInDays > 7 && (
            <span className="flex items-center gap-1 text-amber-600">
              <AlertCircle className="h-4 w-4" />
              Consider refreshing
            </span>
          )}
        </div>
      )}

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        <PeakHoursHeatmap />
        <AnomalyAlerts />
        <AIRecommendations className="lg:col-span-2" />
      </div>
    </div>
  );
}
