/**
 * features.ts — what version one deliberately does not ship.
 *
 * Each flag here is off because shipping it would get the app rejected, not
 * because the code is unfinished. The reasoning lives beside the flag so the
 * person who turns it on knows what has to be true first.
 *
 * A disabled control that explains itself feels honest to us and reads as an
 * unfinished app to a reviewer. App Review Guideline 2.1 covers exactly that:
 * placeholder features, greyed-out buttons, and "coming soon" are rejections.
 * The fix is never a better explanation — it is not shipping the control.
 */

/**
 * Apple and Google sign-in.
 *
 * THE CODE IS FINISHED. This is no longer a placeholder gate — it is the last
 * step of a checklist, and the only remaining item is testing on real hardware.
 *
 * Done:
 *   - Supabase providers Apple and Google both enabled; redirect allow-list
 *     includes `lyne://**`.
 *   - Apple: App ID com.lyne.mobile carries Sign In with Apple; Services ID
 *     com.lyne.mobile.signin; both are in Supabase's Apple "Client IDs".
 *   - Google: Web and iOS OAuth clients exist in project lyne-510522 and are in
 *     Supabase's Google "Client IDs". "Skip nonce checks" is OFF, which is
 *     correct — the Apple path sends a real nonce.
 *   - App code: components/SocialAuthButtons.tsx, lib/socialAuth.ts and
 *     useAuth's signInWithSocial. Apple uses the native sheet on iOS; Google,
 *     and Apple on Android, use the Supabase browser flow.
 *
 * Still outstanding before flipping this:
 *   1. TEST BOTH ON A REAL DEVICE. These are native modules, so that needs a
 *      new EAS build — an OTA update cannot add them.
 *   2. The Google consent screen is still in **Testing** mode, so only accounts
 *      on its test-users list can sign in. Publishing it is what makes Google
 *      sign-in work for the public, and it is a prerequisite for release, not
 *      for testing.
 *
 * NOT outstanding, despite what the old note here said: no Android OAuth client
 * is needed. The browser flow authenticates against the Web client, so nothing
 * waits on a signing-certificate SHA-1 that does not exist until the first
 * Android build. That was the reason this could not ship, and it no longer
 * applies. A SHA-1 client would only be required if the native Google SDK were
 * adopted later.
 *
 * Apple requires Sign in with Apple to be offered wherever another social
 * sign-in is, so these two go live together or not at all — which is why one
 * flag covers both.
 *
 * Diary note: the Apple client secret in Supabase is a JWT with an expiry, not
 * a password. The one generated by secrets/step8-apple-secret.sh dies on
 * 1 April 2027, and Google and Apple sign-in both stop that day unless it is
 * regenerated. See docs/PROVIDER_SETUP.md.
 */
export const SOCIAL_AUTH_ENABLED = false;

/**
 * Lyne Premium — the upsell, the free trial, and the saved-cards screen.
 *
 * Three separate problems, all solved by not showing it in version one:
 *
 * 1. **It cannot complete.** Payments are stubbed on the server, and the
 *    publishable key is empty. Every path ends in failure.
 *
 * 2. **The destination is a 404.** The upgrade flow sends people to
 *    uselyne.com/account, which does not exist on the live site.
 *
 * 3. **Steering outside the store breaks Guideline 3.1.1.** Sending an iOS
 *    customer to a website to pay for digital content is permitted only on the
 *    US storefront, in the EU, South Korea and Japan. **Jamaica is not covered**,
 *    so the app's primary market is exactly where this is prohibited. It is
 *    worth being clear that Claude and ChatGPT do NOT do this on iOS — they
 *    use Apple's in-app purchase. Copying "the big apps" here means copying
 *    IAP, not copying a web link.
 *
 * TO ENABLE: implement StoreKit in-app purchase for iOS and Google Play
 * Billing for Android, confirm Apple supports developer payouts to a Jamaican
 * bank account, then flip this. A web checkout is NOT the route for the
 * consumer subscription.
 *
 * This does not affect the ORGANISATION subscription. That is a business
 * buying administrator software through an invoice or a web checkout, Apple
 * has no jurisdiction over it, and nothing about it is sold inside this app.
 */
export const PREMIUM_ENABLED = false;

/**
 * The 14-day free trial, on its own.
 *
 * Split out of PREMIUM_ENABLED because the two were never the same risk and
 * folding them together hid a feature that works behind one that does not.
 *
 * Starting a trial is a POST to /auth/start-trial. It sets is_premium and
 * premium_until fourteen days out and returns the updated row. No card, no
 * Stripe, no storefront, no web page — it completes every time, today, and it
 * has been tested end to end against the API. So neither of the rules that
 * gate PREMIUM_ENABLED applies to it: Guideline 2.1 is about controls that
 * cannot finish, and this one finishes; 3.1.1 is about steering a customer
 * outside the app to pay, and nothing is being paid.
 *
 * With both behind one flag, a free customer got a paywall with no way past it
 * — the one action we could actually honour was switched off alongside the one
 * we could not. That reads as a broken screen, and it costs the trial starts
 * that are the whole point of having a free tier.
 *
 * CONVERSION after the trial is the part that still needs store billing, and
 * that is what PREMIUM_ENABLED above still gates.
 */
export const PREMIUM_TRIAL_ENABLED = true;

/**
 * The "Add to Apple Wallet" / "Add to Google Wallet" control on the ticket.
 *
 * The feature is worth having and the reason is offline: at the counter the
 * phone may have no signal, and a pass in Wallet scans from the lock screen
 * without the app running at all. None of that is why this is off.
 *
 * It is off because the control cannot work. A signed pass needs an Apple Pass
 * Type ID certificate, and the Android half needs a Google Wallet issuer
 * account; neither exists, and both arrive with store enrolment rather than
 * with a code change. What shipped in the meantime was a button-shaped view
 * with a caption underneath reading "Wallet passes arrive with the App Store
 * release" — which is the exact shape of a Guideline 2.1 rejection: a control
 * that looks finished, does nothing, and explains itself. The explanation is
 * what makes it worse, not better.
 *
 * One thing it did get right, and which is worth not losing when this is
 * turned back on: both the label and the caption followed Platform.OS, so an
 * Android build said "Google Wallet" and "the Play Store release". A control
 * that offers an Android customer an Apple wallet is the kind of detail that
 * tells somebody the app was built for a different phone than the one in their
 * hand. Keep that if the button returns.
 *
 * Nothing is lost by hiding it. The Code 39 barcode above it is what the
 * counter actually scans, and it is real.
 *
 * TO ENABLE: obtain the Apple Pass Type ID certificate and the Google Wallet
 * issuer account, add a backend endpoint that signs a .pkpass and a Google
 * Wallet JWT for a ticket, wire the button to it, and flip this. Until then it
 * renders nothing — not a disabled button, and not a gap where one was.
 */
export const WALLET_PASS_ENABLED = false;
